### ISSUE TITLE
Tests fail with NumPy 1.26.2

### ISSUE THREAD

**Issue by Hellseher** [astroML/astroML#281]
Hi,

After updating NumPy to 1.26.2 in Guix package index I noticed astroML@1.0.2.post1 started
failing with errors in unit tests:

```
============================= test session starts ==============================
platform linux -- Python 3.11.11, pytest-8.3.3, pluggy-1.5.0 -- /gnu/store/y5vz9h983i8cg01cxz0zdywz715fxxs8-python-wrapper-3.11.11/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/tmp/guix-build-python-astroml-1.0.2.post1.drv-0/astroML-1.0.2.post1/.hypothesis/examples')
rootdir: /tmp/guix-build-python-astroml-1.0.2.post1.drv-0/astroML-1.0.2.post1
configfile: setup.cfg
plugins: hypothesis-6.54.5, astropy-header-0.2.2, cov-6.0.0, doctestplus-1.2.1, remotedata-0.4.1
collecting ... collected 203 items / 2 errors

==================================== ERRORS ====================================
_______________ ERROR collecting astroML/tests/test_resample.py ________________
astroML/tests/test_resample.py:2: in <module>
    from numpy.testing import assert_allclose, run_module_suite
E   ImportError: cannot import name 'run_module_suite' from 'numpy.testing' (/gnu/store/h0y4py6lbj1jqw1sbfs504k26jbijdl1-python-numpy-1.26.2/lib/python3.11/site-packages/numpy/testing/__init__.py)
_______________ ERROR collecting astroML/tests/test_resample.py ________________
ImportError while importing test module '/tmp/guix-build-python-astroml-1.0.2.post1.drv-0/astroML-1.0.2.post1/astroML/tests/test_resample.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/gnu/store/svi4rix9hwyq9af0gax9hfc41k9jcyjh-python-pytest-8.3.3/lib/python3.11/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
/gnu/store/svi4rix9hwyq9af0gax9hfc41k9jcyjh-python-pytest-8.3.3/lib/python3.11/site-packages/_pytest/pathlib.py:582: in import_path
    importlib.import_module(module_name)
/gnu/store/h6js234mh24sbgxaz5fq750pq9r8razq-python-3.11.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1204: in _gcd_import
    ???
<frozen importlib._bootstrap>:1176: in _find_and_load
    ???
<frozen importlib._bootstrap>:1147: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
/gnu/store/svi4rix9hwyq9af0gax9hfc41k9jcyjh-python-pytest-8.3.3/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
    exec(co, module.__dict__)
astroML/tests/test_resample.py:2: in <module>
    from numpy.testing import assert_allclose, run_module_suite
E   ImportError: cannot import name 'run_module_suite' from 'numpy.testing' (/gnu/store/h0y4py6lbj1jqw1sbfs504k26jbijdl1-python-numpy-1.26.2/lib/python3.11/site-packages/numpy/testing/__init__.py)
=============================== warnings summary ===============================
../../../gnu/store/svi4rix9hwyq9af0gax9hfc41k9jcyjh-python-pytest-8.3.3/lib/python3.11/site-packages/_pytest/config/__init__.py:1441
  /gnu/store/svi4rix9hwyq9af0gax9hfc41k9jcyjh-python-pytest-8.3.3/lib/python3.11/site-packages/_pytest/config/__init__.py:1441: PytestConfigWarning: Unknown config option: testspaths

    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

astroML/datasets/tools/sdss_fits.py:9
  /tmp/guix-build-python-astroml-1.0.2.post1.drv-0/astroML-1.0.2.post1/astroML/datasets/tools/sdss_fits.py:9: DeprecationWarning: Please import `gaussian_filter1d` from the `scipy.ndimage` namespace; the `scipy.ndimage.filters` namespace is deprecated and will be removed in
 SciPy 2.0.0.
    from scipy.ndimage.filters import gaussian_filter1d, uniform_filter1d

astroML/datasets/tools/sdss_fits.py:9
  /tmp/guix-build-python-astroml-1.0.2.post1.drv-0/astroML-1.0.2.post1/astroML/datasets/tools/sdss_fits.py:9: DeprecationWarning: Please import `uniform_filter1d` from the `scipy.ndimage` namespace; the `scipy.ndimage.filters` namespace is deprecated and will be removed in
SciPy 2.0.0.
    from scipy.ndimage.filters import gaussian_filter1d, uniform_filter1d

astroML/decorators.py:7
  /tmp/guix-build-python-astroml-1.0.2.post1.drv-0/astroML-1.0.2.post1/astroML/decorators.py:7: AstroMLDeprecationWarning: 'decorators' has been moved to 'astroML.utils' and will be removed from the main namespace in the future.
    warnings.warn("'decorators' has been moved to 'astroML.utils' and will be "

astroML/linear_model/linear_regression_errors.py:10
  /tmp/guix-build-python-astroml-1.0.2.post1.drv-0/astroML-1.0.2.post1/astroML/linear_model/linear_regression_errors.py:10: UserWarning: LinearRegressionwithErrors requires PyMC3 to be installed
    warnings.warn('LinearRegressionwithErrors requires PyMC3 to be installed')

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR astroML/tests/test_resample.py - ImportError: cannot import name 'run_module_suite' from 'numpy.testing' (/gnu/store/h0y4py6lbj1jqw1sbfs504k26jbijdl1-python-numpy-1.26.2/lib/python3.11/site-packages/numpy/testing/__init__.py)
ERROR astroML/tests/test_resample.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 5 warnings, 2 errors in 1.81s =========================
```
Inputs:

- python@3.11.11

- python-astroml@1.0.2.post1
  - python-astropy@6.1.7
  - python-matplotlib@3.8.2
  - python-numpy@1.26.2
  - python-pytest-astropy-header@0.2.2
  - python-pytest-cov@6.0.0
  - python-pytest-doctestplus@1.2.1
  - python-pytest-remotedata@0.4.1
  - python-scikit-learn@1.4.2
  - python-scipy@1.12.0
  - python-wheel@0.40.0

**Comment by bsipocz** [comment]
Yeap, this needs some TLC. I'll try to find some time in the near future.
